[tool.poetry]
name = "fastapi_server"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.68.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
